Add Map.filterMap
darklang/tablecloth-ocaml-base pull request #7
Opened 2022-10-13 23:20 UTC by pm5

Moved over from darklang/tablecloth#273.

2022-10-14 18:33 UTC, pbiggar requested changes
Thanks! Made a few notes - might be better to wait until after #6

2022-10-14 18:33 UTC, pbiggar commented on native/src/TableclothMap.ml
> +let filterMap m ~f =
We no longer use camelCase for OCaml

2022-10-14 18:33 UTC, pbiggar commented on rescript/src/TableclothMap.ml
> +let filterMap m ~f =
Rescript is no longer in this repo (it's in https://github.com/darklang/tablecloth-rescript)

2022-10-14 18:33 UTC, pbiggar commented on rescript/src/TableclothMap.ml
> +let filterMap m ~f =
Would love a PR there.

2022-10-14 18:33 UTC, pbiggar commented on rescript/test/MapTest.ml
> +      describe "filterMap" (fun () ->
This test should be for native.

2022-10-23 01:43 UTC, pm5 commented
If we're done with #9 I think this is ready.  I'll move the Rescript part to https://github.com/darklang/tablecloth-rescript

2022-10-23 16:36 UTC, merged

2022-10-23 16:44 UTC, pbiggar commented
Thanks!